rec:
	g++ rectangular.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
shape2:
	g++ shape2.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
shape1:
	g++ shape1.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe