earth:
	g++ earth.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
ensign:
	g++ ensign.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.ex
	
third:
	g++ third.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.ex