Elipse:
	g++ Elipse.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
Helix:
	g++ Helix.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe

Curve:
	g++ Curve.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe