static_square:
	g++ static_square.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe

dynamic_square:
	g++ dynamic_square.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe

static_tet:
	g++ static_tetrahedron.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
dynamic_tet:
	g++ dynamic_tet.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
circle:
	g++ circle.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
dynamic_circle:
	g++ dynamic_circle.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe