LookAt:
	g++ LookAt.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
View:
	g++ View.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
Volume:
	g++ Volume.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe