TriRecur:
	g++ TriRecur.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
TetRecur:
	g++ TetRecur.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
Depth1:
	g++ Depth1.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
Oval:
	g++ Oval.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
Oval1:
	g++ Oval1.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe

cullface:
	g++ cullface.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
tet:
	g++ tet.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
mesh:
	g++ mesh.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe
	
mesh1:
	g++ mesh1.cpp -o run -lfreeglut -lglu32 -lopengl32
	./run
	del run.exe